version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: mysql-rank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_USER: megarank
      MYSQL_PASSWORD: senha1234
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"